require 'stub/default.rb'
require 'stub/defaultMappingRegistry.rb'
require 'soap/rpc/driver'

class ResponsysWS < ::SOAP::RPC::Driver
  # Sun - Changed from 8080 to 80 per Responsys
  DefaultEndpointUrl = "https://ws5.responsys.net/webservices/services/ResponsysWSService"

  Methods = [
    [ "",
      "login",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "login"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "loginResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"AccountFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"AccountFault"}, "UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "authenticateServer",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "authenticateServer"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "authenticateServerResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"AccountFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"AccountFault"}, "UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "loginWithCertificate",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "loginWithCertificate"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "loginWithCertificateResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"AccountFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"AccountFault"}, "UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "logout",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "logout"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "logoutResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "createFolder",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createFolder"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createFolderResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "FolderFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"FolderFault"}} }
    ],
    [ "",
      "deleteFolder",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteFolder"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteFolderResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "FolderFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"FolderFault"}} }
    ],
    [ "",
      "listFolders",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "listFolders"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "listFoldersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "listFolderObjects",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "listFolderObjects"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "listFolderObjectsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "FolderFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"FolderFault"}} }
    ],
    [ "",
      "triggerCampaignMessage",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "triggerCampaignMessage"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "triggerCampaignMessageResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "TriggeredMessageFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"TriggeredMessageFault"}} }
    ],
    [ "",
      "triggerCustomEvent",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "triggerCustomEvent"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "triggerCustomEventResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "CustomEventFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"CustomEventFault"}} }
    ],
    [ "",
      "createCampaign",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createCampaign"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createCampaignResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "CampaignFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"CampaignFault"}} }
    ],
    [ "",
      "setCampaignProperties",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "setCampaignProperties"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "setCampaignPropertiesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "CampaignFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"CampaignFault"}} }
    ],
    [ "",
      "getCampaignProperties",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getCampaignProperties"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getCampaignPropertiesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "CampaignFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"CampaignFault"}} }
    ],
    [ "",
      "launchCampaign",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "launchCampaign"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "launchCampaignResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "CampaignFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"CampaignFault"}} }
    ],
    [ "",
      "scheduleCampaignLaunch",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "scheduleCampaignLaunch"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "scheduleCampaignLaunchResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "CampaignFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"CampaignFault"}} }
    ],
    [ "",
      "getLaunchStatus",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getLaunchStatus"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getLaunchStatusResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "CampaignFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"CampaignFault"}} }
    ],
    [ "",
      "getCampaignId",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getCampaignId"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getCampaignIdResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "CampaignFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"CampaignFault"}} }
    ],
    [ "",
      "deleteCampaign",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteCampaign"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteCampaignResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "CampaignFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"CampaignFault"}} }
    ],
    [ "",
      "getLaunchesForCampaign",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getLaunchesForCampaign"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getLaunchesForCampaignResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "CampaignFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"CampaignFault"}} }
    ],
    [ "",
      "getOpenLaunches",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getOpenLaunches"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getOpenLaunchesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"AccountFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"AccountFault"}, "UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "closeCampaign",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "closeCampaign"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "closeCampaignResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "CampaignFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"CampaignFault"}} }
    ],
    [ "",
      "unscheduleCampaignLaunch",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "unscheduleCampaignLaunch"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "unscheduleCampaignLaunchResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "CampaignFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"CampaignFault"}} }
    ],
    [ "",
      "createList",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createList"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createListResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ListFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ListFault"}} }
    ],
    [ "",
      "changeListSchema",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "changeListSchema"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "changeListSchemaResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ListFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ListFault"}} }
    ],
    [ "",
      "deleteList",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteList"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteListResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ListFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ListFault"}} }
    ],
    [ "",
      "mergeListMembers",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "mergeListMembers"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "mergeListMembersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ListFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ListFault"}} }
    ],
    [ "",
      "retrieveListMembers",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "retrieveListMembers"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "retrieveListMembersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ListFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ListFault"}} }
    ],
    [ "",
      "deleteListMembers",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteListMembers"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteListMembersResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ListFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ListFault"}} }
    ],
    [ "",
      "getUpdated",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getUpdated"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getUpdatedResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ListFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ListFault"}} }
    ],
    [ "",
      "createTable",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createTable"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createTableResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"TableFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"TableFault"}, "UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "deleteTable",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteTable"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteTableResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"TableFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"TableFault"}, "UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "changeTableSchema",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "changeTableSchema"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "changeTableSchemaResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"TableFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"TableFault"}, "UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "mergeTableRecords",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "mergeTableRecords"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "mergeTableRecordsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"TableFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"TableFault"}, "UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "mergeTableRecordsWithPK",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "mergeTableRecordsWithPK"], true],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "mergeTableRecordsWithPKResponse"], true] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal }
    ],
    [ "",
      "retrieveTableRecords",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "retrieveTableRecords"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "retrieveTableRecordsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"TableFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"TableFault"}, "UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "deleteTableRecords",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteTableRecords"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteTableRecordsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"TableFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"TableFault"}, "UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "truncateTable",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "truncateTable"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "truncateTableResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"TableFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"TableFault"}, "UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "createSQLView",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createSQLView"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createSQLViewResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"TableFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"TableFault"}, "UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "createLinkTable",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createLinkTable"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createLinkTableResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "LinkTableFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"LinkTableFault"}} }
    ],
    [ "",
      "deleteLinkTable",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteLinkTable"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteLinkTableResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "LinkTableFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"LinkTableFault"}} }
    ],
    [ "",
      "mergeLinkRecords",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "mergeLinkRecords"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "mergeLinkRecordsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "LinkTableFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"LinkTableFault"}} }
    ],
    [ "",
      "retrieveLinkRecords",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "retrieveLinkRecords"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "retrieveLinkRecordsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "LinkTableFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"LinkTableFault"}} }
    ],
    [ "",
      "deleteLinkRecords",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteLinkRecords"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteLinkRecordsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "LinkTableFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"LinkTableFault"}} }
    ],
    [ "",
      "createDocument",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createDocument"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "createDocumentResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "DocumentFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"DocumentFault"}} }
    ],
    [ "",
      "deleteDocument",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteDocument"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "deleteDocumentResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "DocumentFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"DocumentFault"}} }
    ],
    [ "",
      "setDocumentImages",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "setDocumentImages"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "setDocumentImagesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "DocumentFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"DocumentFault"}} }
    ],
    [ "",
      "getDocumentImages",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getDocumentImages"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getDocumentImagesResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "DocumentFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"DocumentFault"}} }
    ],
    [ "",
      "setDocumentContent",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "setDocumentContent"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "setDocumentContentResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "DocumentFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"DocumentFault"}} }
    ],
    [ "",
      "getDocumentContent",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getDocumentContent"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getDocumentContentResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "DocumentFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"DocumentFault"}} }
    ],
    [ "",
      "copy",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "copy"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "copyResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ObjectFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ObjectFault"}} }
    ],
    [ "",
      "move",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "move"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "moveResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ObjectFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ObjectFault"}} }
    ],
    [ "",
      "getServerTimestamp",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getServerTimestamp"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getServerTimestampResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}} }
    ],
    [ "",
      "describeObjects",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "describeObjects"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "describeObjectsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ObjectFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ObjectFault"}} }
    ],
    [ "",
      "runJob",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "runJob"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "runJobResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ConnectFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ConnectFault"}} }
    ],
    [ "",
      "getJobRunStatus",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getJobRunStatus"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getJobRunStatusResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ConnectFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ConnectFault"}} }
    ],
    [ "",
      "getJobs",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getJobs"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getJobsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ConnectFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ConnectFault"}} }
    ],
    [ "",
      "getJobRuns",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getJobRuns"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getJobRunsResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ConnectFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ConnectFault"}} }
    ],
    [ "",
      "getJobRunLog",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getJobRunLog"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "getJobRunLogResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ConnectFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ConnectFault"}} }
    ],
    [ "",
      "mergeListMembersRIID",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "mergeListMembersRIID"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "mergeListMembersRIIDResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ListFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ListFault"}} }
    ],
    [ "",
      "mergeIntoProfileExtension",
      [ ["in", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "mergeIntoProfileExtension"]],
        ["out", "parameters", ["::SOAP::SOAPElement", "urn:ws.rsys.com", "mergeIntoProfileExtensionResponse"]] ],
      { :request_style =>  :document, :request_use =>  :literal,
        :response_style => :document, :response_use => :literal,
        :faults => {"UnexpectedErrorFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"UnexpectedErrorFault"}, "ListExtensionFault_"=>{:ns=>"urn:ws.rsys.com", :use=>"literal", :namespace=>nil, :encodingstyle=>"document", :name=>"ListExtensionFault"}} }
    ]
  ]

  def initialize(endpoint_url = nil)
    endpoint_url ||= DefaultEndpointUrl
    super(endpoint_url, nil)
    self.mapping_registry = DefaultMappingRegistry::EncodedRegistry
    self.literal_mapping_registry = DefaultMappingRegistry::LiteralRegistry
    init_methods
  end

private

  def init_methods
    Methods.each do |definitions|
      opt = definitions.last
      if opt[:request_style] == :document
        add_document_operation(*definitions)
      else
        add_rpc_operation(*definitions)
        qname = definitions[0]
        name = definitions[2]
        if qname.name != name and qname.name.capitalize == name.capitalize
          ::SOAP::Mapping.define_singleton_method(self, qname.name) do |*arg|
            __send__(name, *arg)
          end
        end
      end
    end
  end
end

